---
title: "BE Group Submission Assignment 4"
subtitle: "Group 15" 
author: "Kacper Kaznowski (2803584), Lanlan Hou (2801069) and Alfred Sou (2796840)"
output: pdf_document
---

# Question 1

## a.
```{r echo=TRUE,fig.dim=c(6,4),fig.align='center'}
# Load required packages
library(openxlsx)   # Excel file handling
library(ggplot2)    # Data visualization
library(mvtnorm)    # 

raw <- read.xlsx('Assignment4Dataset.xlsx', colNames = TRUE)

gdpPlot <- function (input_date, input_y, input_title, input_path){
  plot_df <- data.frame(time = input_date, gdp_forecast = input_y)
  
  ggplot(plot_df, aes(x = time)) +
  geom_hline(yintercept = 0, color = 'black', 
             linewidth = 1, linetype = 'dashed') +
  geom_line(aes(y = gdp_forecast), color = 'red', 
            linewidth = 1) +
  labs(title = input_title,
    x = 'Time', y = 'GDP') +
  theme_minimal()

  ggsave(input_path, width = 10, height = 5, dpi = 300)
}

gdpPlot(raw[['time']], raw[['y_t']], 'Forecasting real US GDP growth using Autoregressive (AR) models', 'figures/a_gdp.png')
```

## b.
```{r echo=TRUE,fig.dim=c(6,4),fig.align='center'}
colnames(raw) <- c('time', 'y_t', 'y_lag1', 'y_lag2')

ar2_gdp <- lm(formula = y_t ~ `y_lag1` + `y_lag2`, 
              data = raw)

ar2_estimation <- summary(ar2_gdp)

last_row <- raw[nrow(raw),]

new_df <- data.frame(`y_lag1` = last_row$`y_t`,
                     `y_lag2` = last_row$`y_lag1`)

y_tPlus1 <- predict(ar2_gdp, newdata = new_df)

s <- ar2_estimation$sigma

y_tPlus1_95_lowerBound <- y_tPlus1 - 1.96*s
y_tPlus1_95_upperBound <- y_tPlus1 + 1.96*s

cat(sprintf('The prediction of y_{t+1} is %.4f.\n', y_tPlus1))
cat(sprintf('95%% prediction interval is [%.4f, %.4f].\n',
            y_tPlus1_95_lowerBound,
            y_tPlus1_95_upperBound))
```

## c.
```{r echo=TRUE,fig.dim=c(6,4),fig.align='center'}
numberOfSimulations <- 10000

this_y <- c(1, last_row$`y_t`, last_row$`y_lag1`)
hat_beta <- coef(ar2_gdp)
covarianceMatrix <- ar2_estimation$cov.unscaled
degreeOfFreedom <- ar2_estimation$df[2]
sizeOfSample <- length(raw[['time']])

y_tPlus1_simulation <- numeric(numberOfSimulations)

for (i in 1:numberOfSimulations){
  beta_i <- rmvt(n = 1, 
                 sigma = covarianceMatrix,
                 df = degreeOfFreedom, 
                 delta = hat_beta, type = 'shifted')
  beta_i <- as.numeric(beta_i)        # length p
  beta_i <- matrix(beta_i, ncol = 1)  
  
  y <- raw[['y_t']]
  X <- model.matrix(ar2_gdp)
  residual <- y - X %*% beta_i
  
  this_scale <- 1/(1/2 * t(residual) %*% residual)
    
  h_i <- rgamma(n = 1, shape = sizeOfSample/2 , scale = this_scale)
  
  residuals_i <- rnorm(n = 1, mean = 0, sd = sqrt(1/h_i))
  
  this_hat_y_tPlus1 <- sum(this_y * hat_beta)
  
  y_tPlus1_simulation[i] <- this_hat_y_tPlus1 + residuals_i
}

bayesian_mean <- mean(y_tPlus1_simulation)
bayesian_95_lowerBound <- quantile(y_tPlus1_simulation, 0.025)
bayesian_95_upperBound<- quantile(y_tPlus1_simulation, 0.975)

print('Bayesian prediction:')
cat(sprintf('The prediction of y_{t+1} is %.4f.\n', bayesian_mean))
cat(sprintf('95%% prediction interval is [%.4f, %.4f].\n',
            bayesian_95_lowerBound,
            bayesian_95_upperBound))
```

## d.
```{r echo=TRUE,fig.dim=c(6,4),fig.align='center'}
```