---
title: "BE Group Submission Assignment 1"
subtitle: "Group 15" 
author: "Lanlan Hou (2801069), Sebastiaan van Dijen (2769505) and Alfred Sou (2796840)"
output: pdf_document
---

# Question 1

## a.
```{r echo=TRUE,fig.dim=c(6,4),fig.align='center'}
sampleData <- c(1.6088,-1.4579,0.4502,1.0701,-0.3803,1.1201,0.4199,0.3998,-0.1904,0.3932)
numberOfSimulations <- 11000
numberOfBurnIn <- 1000
initial_mu <- mean(sampleData)
numberOfSample <- length(sampleData)

h_list <- numeric(numberOfSimulations)
mu_list <- numeric(numberOfSimulations)

# Gibbs sampling
for (i in 1:numberOfSimulations) {
  a <- numberOfSample / 2
  
  if (i-1 == 0){
    b <- 1 / (1/2 * sum(sapply(1:numberOfSample, 
                               function(j) (sampleData[j] - initial_mu)^2)))
  } else {
    b <- 1 / (1/2 * sum(sapply(1:numberOfSample, 
                               function(j) (sampleData[j] - mu_list[i-1])^2)))
  }
  
  bar_y <- mean(sampleData)
  
  # draw from Gamma distribution
  h_list[i] <- rgamma(n = 1, shape = a, scale = b)
  
  # draw from Normal distribution
  mu_list[i] <- rnorm(n = 1, mean = bar_y, 
                      sd = sqrt(1/(h_list[i] * numberOfSample)))
}

# Trace plot of µ
serialNumber <- seq(from=1, to=numberOfSimulations, by=1)
plot(serialNumber, mu_list, type='l', col='blue',
     main='Trace plot of µ', xlab='Draw', ylab='µ')

# estimate the posterior probabilities
print('The posterior probabilities are:')
sum_mu_greater_0 <- sum(mu_list[numberOfBurnIn:numberOfSimulations] > 0)
print(paste('Pr(µ > 0 | y) =', sum_mu_greater_0/(numberOfSimulations-numberOfBurnIn)))

sum_mu_less_0 <- sum(mu_list[numberOfBurnIn:numberOfSimulations] < 0)
print(paste('Pr(µ < 0 | y) =', sum_mu_less_0/(numberOfSimulations-numberOfBurnIn)))
```

## b.
```{r echo=TRUE,fig.dim=c(6,4),fig.align='center'}

```