---
title: "BE Group Submission Assignment 1"
subtitle: "Group 15" 
author: "Kacper Kaznowski (2803584), Lanlan Hou (2801069) and Alfred Sou (2796840)"
output: pdf_document
---

# Question 1

## a.
```{r echo=TRUE,fig.dim=c(6,4),fig.align='center'}
library(ggplot2)

rawData <- read.csv('Assignment2Dataset.csv')
input_returns <- rawData[[1]]

df <- data.frame(date = seq_along(input_returns), returns = input_returns)

ggplot(df, aes(x = date, y = returns)) +
  geom_line(color = 'blue') +
  geom_hline(yintercept = 0, color = 'black', linetype = 'dashed', linewidth = 1) +
  labs(title = 'Daily returns of the S&P 500 in the six years 2018-2023',
       x = 'Date', y = 'Daily returns') +
  theme_minimal()
ggsave('figures/a_returns_plot.png', width = 10, height = 6, dpi = 300)
```

## b.
```{r echo=TRUE,fig.dim=c(6,4),fig.align='center'}
numberOfSimulations <- 1100
numberOfBurnIn <- 100

initial_alpha <- 0.4745

b_stdev <- 0.0275

logLikelihood <- function(input_alpha){
  n <- length(input_returns)
  s_squared <- var(input_returns)
  
  result <- sum(sapply(2:n, function(j) 
    -1/2 * log(2*pi * (s_squared * (1-input_alpha) + input_alpha * input_returns[j-1]^2)) 
    -1/2 * (input_returns[j]^2 / (s_squared * (1-input_alpha) + input_alpha * input_returns[j-1]^2))))
  
  return (result)
}

metropolisHastings_method_norm <- function (input_stdev){
  alpha_list <- numeric(numberOfSimulations)
  
  for (i in 1:numberOfSimulations) {
    # draw from Normal distribution
    if(i == 1){
      this_alpha <- rnorm(n = 1, mean = initial_alpha, sd = input_stdev)
    } else{
      this_alpha <- rnorm(n = 1, mean = alpha_list[i-1], sd = input_stdev)
    }
    
    if (this_alpha < 0 || this_alpha > 1) {
      acceptance = 0
    } else {
      if(i == 1){
        acceptance = 1
      } else { 
        logLikelihood_this <- logLikelihood(this_alpha)
        logLikelihood_previous <- logLikelihood(alpha_list[i-1])
      
        acceptance = min(1, exp(logLikelihood_this - logLikelihood_previous))
      }
    }
      
    u <- runif(1, min = 0, max = 1)
    
    if (u <= acceptance){
      alpha_list[i] <- this_alpha
    } else {
      if(i == 1){
        alpha_list[i] <- initial_alpha
      } else{
        alpha_list[i] <- alpha_list[i-1]
      }
    }
  }
  return (alpha_list)
}

b_alpha_list <- metropolisHastings_method_norm(b_stdev)

alpha_list_afterBurn <- b_alpha_list[(numberOfBurnIn+1):length(b_alpha_list)]

tracePlot <- function (input_x, input_title, input_path){
  plot_df <- data.frame(x = seq_along(input_x), y = input_x)
  
  ggplot(plot_df, aes(x = x, y = y)) +
  geom_line(color = 'blue') +
  geom_vline(xintercept = initial_alpha, color = 'black', linetype = 'dashed', linewidth = 1) +
  labs(title = input_title,
       x = 'Iteration', y = 'Alpha') +
  theme_minimal()
ggsave(input_path, width = 10, height = 6, dpi = 300)
}

distributionPlot <- function (input_x, input_title, input_path){
  plot_df <- data.frame(x = seq_along(input_x), y = input_x)
  
  ggplot(plot_df, aes(x = y)) +
    geom_histogram(aes(y = after_stat(density), color = 'Empirical Distribution'),
                   bins = 50, fill = 'skyblue') +
    stat_function(fun = dnorm,
                  args = list(mean = mean(plot_df$y), sd = sd(plot_df$y)),
                  aes(color = 'Normal Distribution')
                  , linewidth = 1, linetype = 'dashed') +
    geom_vline(aes(xintercept = initial_alpha, color = "Initial α"), 
               linetype = 'dashed', linewidth = 1) +
    labs(title = input_title,
       x = 'α', y = 'Density') +
    theme_minimal() +
    scale_color_manual(name   = 'Component',
                       values = c('Empirical Distribution' = 'blue',
                                  'Normal Distribution' = 'red',
                                  'Initial α' = 'black'))
  ggsave(input_path, width = 10, height = 6, dpi = 300)
}

tracePlot(alpha_list_afterBurn, 'Trace plot of draws α', 'figures/b_alpha_trace.png')
distributionPlot(alpha_list_afterBurn, 'Distribution of draws α', 'figures/b_alpha_hist.png')

posterior_mean <- mean(alpha_list_afterBurn)
posterior_stdev <- sd(alpha_list_afterBurn)

posterior_mean
posterior_stdev
```

## c.
```{r echo=TRUE,fig.dim=c(6,4),fig.align='center'}
c_stdev <- 0.002

c_alpha_list <- metropolisHastings_method_norm(c_stdev)

alpha_list_afterBurn <- c_alpha_list[(numberOfBurnIn+1):length(c_alpha_list)]

tracePlot(alpha_list_afterBurn, 'Trace plot of draws α', 'figures/c_alpha_trace.png')
distributionPlot(alpha_list_afterBurn, 'Distribution of draws α', 'figures/c_alpha_hist.png')

posterior_mean <- mean(alpha_list_afterBurn)
posterior_stdev <- sd(alpha_list_afterBurn)

posterior_mean
posterior_stdev
```

## d.
```{r echo=TRUE,fig.dim=c(6,4),fig.align='center'}
d_stdev <- 6

d_alpha_list <- metropolisHastings_method_norm(d_stdev)

alpha_list_afterBurn <- d_alpha_list[(numberOfBurnIn+1):length(d_alpha_list)]

tracePlot(alpha_list_afterBurn, 'Trace plot of draws α', 'figures/d_alpha_trace.png')
distributionPlot(alpha_list_afterBurn, 'Distribution of draws α', 'figures/d_alpha_hist.png')

posterior_mean <- mean(alpha_list_afterBurn)
posterior_stdev <- sd(alpha_list_afterBurn)

posterior_mean
posterior_stdev
```

## e.
```{r echo=TRUE,fig.dim=c(6,4),fig.align='center'}

```

## f.
```{r echo=TRUE,fig.dim=c(6,4),fig.align='center'}

```
